RegisterCommand("info", function()
     exports['mythic_notify']:DoLongHudText('inform', '📣 Discord: [YOUROWNLINK]')
Citizen.Wait(500)
     exports['mythic_notify']:DoLongHudText('inform', '📣 Website: [YOUROWNLINK2]')
     TriggerEvent('chat:addSuggestion', '/info', 'Visit our Website or Join our Discord server!')
end, false)
